{% set name = "pycppad" %}
{% set version = "1.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Simple-Robotics/{{ name }}/releases/download/v{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: 31c042a132a9f6cc17d15b9a12a90f7118126707c4e5d5eff677644ae746c345

build:
  number: 2
  skip: true  # [win and vc<14]

requirements:
  build:
    - {{ compiler('cxx') }}
    - vs2017_win-64  # [win64]
    - vs2017_win-32  # [win32]
    - cmake
    - make  # [not win]
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
  host:
    - eigen
    - boost
    - python
    - cppad
    - cppadcodegen  # [not win]
    - eigenpy
    - numpy
  run:
    - eigen
    - boost
    - python
    - cppad
    - cppadcodegen  # [not win]
    - eigenpy
    - {{ pin_compatible('numpy') }}

test:
  requires:
    - pkg-config
  imports:
    - pycppad
  commands:
    - pkg-config --modversion pycppad

about:
  home: http://github.com/Simple-Robotics/pycppad
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Python bindings for CppAD and CppADCodeGen using Boost.Python
  dev_url: http://github.com/Simple-Robotics/pycppad

extra:
  recipe-maintainers:
    - proyan
    - jcarpent
