{% set name = "pycppad" %}
{% set version = "1.2.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Simple-Robotics/{{ name }}/releases/download/v{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9f5c25f9d35b6d9cd1b99a25a5e8931f60967fe18813c791c6a8dda78625c019

build:
  number: 10
  skip: true  # [(win and vc<14) or (python_impl == 'pypy')]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake
    - ninja
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
  host:
    - eigen
    - libboost-python-devel
    - python
    - cppad
    - cppadcodegen  # [not win and not aarch64 and not ppc64le]
    - eigenpy
    # On Windows, Numpy 2.0 don't allow to export the PY_ARRAY_UNIQUE_SYMBOL.
    # This has been fixed in Numpy 2.1.
    - numpy >=2.1      # [win and py>=310]
    # Unfortunatly, Numpy 2.1 is not distributed with Python 3.9.
    # We are forced to use Numpy 1 in this case.
    - numpy >=1.19,<2  # [win and py<310]
    - numpy            # [not win]
  run:
    - python
    - numpy >=2.1                    # [win and py>=310]
    - {{ pin_compatible('numpy') }}  # [win and py<310]

test:
  requires:
    - pkg-config
  imports:
    - pycppad
  commands:
    - pkg-config --modversion pycppad

about:
  home: http://github.com/Simple-Robotics/pycppad
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Python bindings for CppAD and CppADCodeGen using Boost.Python
  dev_url: http://github.com/Simple-Robotics/pycppad

extra:
  recipe-maintainers:
    - olivier-roussel
    - jorisv
    - proyan
    - jcarpent
